// src/components/hero.tsx
/**
 * 首页顶部Hero区域组件
 * 显示网站标题、副标题和主要行动按钮，是用户访问首页时看到的第一个主要内容区
 */
import React from "react";
import { Button } from "@heroui/react";
import { Icon } from "@iconify/react";
import { motion } from "framer-motion";

export const Hero = ({ setCurrentPage }) => {
  const handleVitePressClick = () => {
    setCurrentPage("docs");
  };
  
  return (
    <section className="hero-gradient py-16 md:py-24 px-4">
      <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between">
        <div className="md:w-1/2 mb-10 md:mb-0">
          <motion.h1 
            className="text-4xl md:text-5xl font-bold mb-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <span className="bg-gradient-to-r from-vp-blue to-vp-purple bg-clip-text text-transparent">VitePress</span>
            <div className="text-vp-text dark:text-white mt-2">
              由 Vite 和 Vue 驱动的<br />
              静态站点生成器
            </div>
          </motion.h1>
          
          <motion.p 
            className="text-lg text-default-700 dark:text-zinc-300 mb-8"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
          >
            将 Markdown 变成优雅的文档，只需几分钟
          </motion.p>
          
          <motion.div 
            className="flex flex-wrap gap-4"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            <Button 
              color="primary" 
              size="lg" 
              radius="md"
              className="font-medium"
              onClick={handleVitePressClick}
            >
              什么是 VitePress?
            </Button>
            <Button 
              variant="flat" 
              size="lg" 
              radius="md"
              className="font-medium"
            >
              快速开始
            </Button>
            <Button 
              variant="flat" 
              size="lg" 
              radius="md"
              className="font-medium"
              startContent={<Icon icon="lucide:github" />}
            >
              GitHub
            </Button>
          </motion.div>
        </div>
        
        <motion.div 
          className="md:w-1/2 flex justify-center"
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6, delay: 0.3 }}
        >
          <div className="relative w-[280px] h-[320px] md:w-[320px] md:h-[360px]">
            <div className="absolute inset-0 bg-gradient-to-br from-blue-500/20 to-purple-500/20 dark:from-blue-500/10 dark:to-purple-500/10 rounded-3xl shadow-lg transform rotate-3"></div>
            <div className="absolute inset-0 bg-white dark:bg-zinc-900 rounded-3xl shadow-md flex items-center justify-center p-6 transform -rotate-3">
              <div className="flex flex-col items-center">
                <Icon icon="logos:vitejs" className="text-6xl mb-4" />
                <div className="text-blue-600 dark:text-blue-400 text-5xl font-bold mb-4">M↓</div>
                <div className="w-16 h-1 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full"></div>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
};

// vitepress-project/docs/.vitepress/theme/components/Hero.vue
<template>
  <section class="w-full py-16 md:py-24 lg:py-32 hero-gradient">
    <div class="container mx-auto px-4 md:px-6">
      <div class="flex flex-col items-center space-y-6 text-center">
        <div class="space-y-3">
          <h1 class="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl bg-clip-text text-transparent bg-gradient-to-r from-indigo-500 to-purple-600">
            VitePress
          </h1>
          <p class="mx-auto max-w-[700px] text-xl text-gray-600 dark:text-gray-300 md:text-2xl">
            由 Vite 和 Vue 驱动的静态站点生成器
          </p>
        </div>
        <div class="flex flex-col gap-3 sm:flex-row">
          <a href="/introduction/" class="inline-flex h-12 items-center justify-center rounded-md bg-indigo-600 px-8 text-sm font-medium text-white shadow transition-colors hover:bg-indigo-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">
            快速开始
          </a>
          <a href="https://github.com/vuejs/vitepress" class="inline-flex h-12 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-950 dark:border-zinc-800 dark:bg-zinc-950 dark:hover:bg-zinc-900 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300">
            <Icon icon="lucide:github" class="mr-2 h-5 w-5" />
            GitHub
          </a>
        </div>
        <div class="flex items-center justify-center space-x-4 mt-8">
          <div class="flex items-center space-x-1">
            <Icon icon="lucide:zap" class="h-5 w-5 text-amber-500" />
            <span class="text-sm font-medium">极速开发体验</span>
          </div>
          <div class="h-4 border-l border-gray-300 dark:border-zinc-700"></div>
          <div class="flex items-center space-x-1">
            <Icon icon="lucide:code" class="h-5 w-5 text-indigo-500" />
            <span class="text-sm font-medium">Markdown 增强</span>
          </div>
          <div class="h-4 border-l border-gray-300 dark:border-zinc-700 hidden sm:block"></div>
          <div class="hidden sm:flex items-center space-x-1">
            <Icon icon="lucide:layout-template" class="h-5 w-5 text-green-500" />
            <span class="text-sm font-medium">主题定制</span>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { Icon } from '@iconify/vue'
</script>

<style scoped>
.hero-gradient {
  background: linear-gradient(to bottom right, rgba(79, 70, 229, 0.1), rgba(219, 39, 119, 0.1));
}
</style>
