// src/components/sidebar.tsx
/**
 * 文档页面左侧侧边栏组件
 * 提供文档的分类导航和目录结构，负责处理文档页面的导航交互
 */
import React from "react";
import { Link, Accordion, AccordionItem } from "@heroui/react";
import { Icon } from "@iconify/react";

const sidebarItems = [
  {
    title: "简介",
    items: [
      { label: "什么是 VitePress?", href: "#what-is-vitepress", id: "what-is-vitepress" },
      { label: "快速开始", href: "#getting-started", id: "getting-started" },
      { label: "路由", href: "#routing", id: "routing" },
      { label: "部署", href: "#deployment", id: "deployment" }
    ]
  },
  {
    title: "写作",
    items: [
      { label: "Markdown 扩展", href: "#markdown", id: "markdown" },
      { label: "资源处理", href: "#asset-handling", id: "asset-handling" },
      { label: "frontmatter", href: "#frontmatter", id: "frontmatter" },
      { label: "在 Markdown 使用 Vue", href: "#using-vue", id: "using-vue" },
      { label: "国际化", href: "#i18n", id: "i18n" }
    ]
  },
  {
    title: "自定义",
    items: [
      { label: "自定义主题", href: "#custom-theme", id: "custom-theme" },
      { label: "扩展默认主题", href: "#extending-default-theme", id: "extending-default-theme" },
      { label: "构建时数据加载", href: "#build-data", id: "build-data" },
      { label: "SSR 兼容性", href: "#ssr-compat", id: "ssr-compat" },
      { label: "选择 CMS", href: "#cms", id: "cms" }
    ]
  },
  {
    title: "实验性功能",
    items: [
      { label: "MPA 模式", href: "#mpa", id: "mpa" }
    ]
  }
];

export const Sidebar = ({ currentPage, setCurrentPage, activeItem, setActiveItem }) => {
  const [isOpen, setIsOpen] = React.useState(false);
  
  return (
    <>
      {/* Mobile sidebar toggle */}
      <div className="fixed bottom-6 right-6 z-40 md:hidden">
        <button 
          onClick={() => setIsOpen(!isOpen)}
          className="bg-primary rounded-full p-3 text-white shadow-lg"
        >
          <Icon icon={isOpen ? "lucide:x" : "lucide:menu"} width={24} height={24} />
        </button>
      </div>
      
      {/* Mobile sidebar overlay */}
      {isOpen && (
        <div 
          className="fixed inset-0 bg-black/50 z-30 md:hidden"
          onClick={() => setIsOpen(false)}
        />
      )}
      
      {/* Sidebar */}
      <aside 
        className={`
          fixed top-0 left-0 z-40 w-64 h-[100vh] bg-white dark:bg-zinc-900 border-r border-gray-200 dark:border-zinc-800
          md:sticky md:top-16 md:h-[calc(100vh-64px)]
          transform transition-transform duration-300 ease-in-out md:translate-x-0
          ${isOpen ? 'translate-x-0' : '-translate-x-full md:translate-x-0'}
        `}
      >
        <div className="p-4 h-[60px] flex items-center border-b border-gray-200 dark:border-zinc-800 md:hidden">
          <div className="flex items-center gap-2">
            <Icon icon="logos:vitejs" className="text-2xl" />
            <span className="font-bold text-lg">VitePress</span>
          </div>
        </div>
        
        <div className="p-4 overflow-y-auto h-[calc(100vh-60px)] md:h-[calc(100vh-64px)]">
          <div className="flex flex-col gap-2">
            {sidebarItems.map((section, index) => (
              <div key={index} className="mb-3">
                <h3 className="text-sm font-medium text-default-700 dark:text-zinc-300 mb-2 px-2">
                  {section.title}
                </h3>
                <div className="flex flex-col gap-0.5">
                  {section.items.map((item, itemIndex) => (
                    <Link
                      key={itemIndex}
                      href={item.href}
                      className={`text-sm py-1 px-3 rounded-md ${
                        activeItem === item.id 
                          ? "bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 font-medium" 
                          : "text-gray-700 dark:text-zinc-400 hover:text-blue-600 dark:hover:text-blue-400 hover:bg-gray-100 dark:hover:bg-zinc-800"
                      }`}
                      onClick={(e) => {
                        e.preventDefault();
                        setActiveItem(item.id);
                        setCurrentPage("docs");
                        setIsOpen(false);
                      }}
                    >
                      {item.label}
                    </Link>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </aside>
    </>
  );
};

// vitepress-project/docs/.vitepress/theme/components/Sidebar.vue
<template>
  <aside class="w-full md:w-64 border-r border-gray-200 dark:border-zinc-800 md:h-[calc(100vh-4rem)] md:sticky md:top-16 overflow-y-auto bg-gray-50 dark:bg-zinc-900/50">
    <div class="p-5 md:p-6">
      <div class="flex justify-between items-center mb-6 md:hidden">
        <h2 class="text-lg font-bold">导航</h2>
        <button @click="isOpen = !isOpen" class="md:hidden p-3 rounded-md hover:bg-gray-200 dark:hover:bg-zinc-800 touch-manipulation">
          <Icon :icon="isOpen ? 'lucide:chevron-up' : 'lucide:chevron-down'" class="h-6 w-6" />
        </button>
      </div>
      
      <div :class="['md:block', { 'hidden': !isOpen }]">
        <div class="space-y-8">
          <!-- 介绍部分 -->
          <div class="space-y-4">
            <div class="flex items-center justify-between">
              <button @click="toggleSection('introduction')" class="w-full py-3 text-sm font-semibold flex items-center text-gray-800 dark:text-gray-200 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors touch-manipulation">
                <Icon :icon="openSections.introduction ? 'lucide:chevron-down' : 'lucide:chevron-right'" class="mr-2 h-5 w-5" />
                介绍
              </button>
            </div>
            <div v-if="openSections.introduction" class="ml-6 space-y-3 border-l-2 border-gray-200 dark:border-zinc-700 pl-3">
              <a href="/introduction/" class="block py-2 px-2 text-sm text-gray-600 dark:text-zinc-400 hover:text-indigo-500 dark:hover:text-indigo-400 transition-colors touch-manipulation" :class="{ 'text-indigo-600 dark:text-indigo-400 font-medium': route.path === '/introduction/' }">
                什么是VitePress
              </a>
              <a href="/introduction/getting-started" class="block py-2 px-2 text-sm text-gray-600 dark:text-zinc-400 hover:text-indigo-500 dark:hover:text-indigo-400 transition-colors touch-manipulation" :class="{ 'text-indigo-600 dark:text-indigo-400 font-medium': route.path === '/introduction/getting-started' }">
                快速开始
              </a>
            </div>
          </div>
          
          <!-- 编写部分 -->
          <div class="space-y-4">
            <div class="flex items-center justify-between">
              <button @click="toggleSection('writing')" class="w-full py-3 text-sm font-semibold flex items-center text-gray-800 dark:text-gray-200 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors touch-manipulation">
                <Icon :icon="openSections.writing ? 'lucide:chevron-down' : 'lucide:chevron-right'" class="mr-2 h-5 w-5" />
                编写
              </button>
            </div>
            <div v-if="openSections.writing" class="ml-6 space-y-3 border-l-2 border-gray-200 dark:border-zinc-700 pl-3">
              <a href="/writing/markdown" class="block py-2 px-2 text-sm text-gray-600 dark:text-zinc-400 hover:text-indigo-500 dark:hover:text-indigo-400 transition-colors touch-manipulation" :class="{ 'text-indigo-600 dark:text-indigo-400 font-medium': route.path === '/writing/markdown' }">
                Markdown
              </a>
              <a href="/writing/asset-handling" class="block py-2 px-2 text-sm text-gray-600 dark:text-zinc-400 hover:text-indigo-500 dark:hover:text-indigo-400 transition-colors touch-manipulation" :class="{ 'text-indigo-600 dark:text-indigo-400 font-medium': route.path === '/writing/asset-handling' }">
                资源处理
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </aside>
</template>

<script setup>
import { ref, watch } from 'vue'
import { useRouter } from 'vitepress'
import { Icon } from '@iconify/vue'

const router = useRouter()
const route = router.route

const isOpen = ref(true)
const openSections = ref({
  introduction: true,
  writing: route.path.startsWith('/writing/'),
})

function toggleSection(section) {
  openSections.value[section] = !openSections.value[section]
}

// 路由变化时自动展开相应的部分
watch(() => route.path, (newPath) => {
  if (newPath.startsWith('/introduction/')) {
    openSections.value.introduction = true
  } else if (newPath.startsWith('/writing/')) {
    openSections.value.writing = true
  }
})
</script>

<style scoped>
/* 添加触摸友好样式 */
.touch-manipulation {
  touch-action: manipulation;
}

/* 增加侧边栏链接项的视觉间距 */
@media (max-width: 767px) {
  a {
    display: block;
    margin-bottom: 0.5rem;
  }
  
  /* 添加触摸反馈效果 */
  a:active, button:active {
    background-color: rgba(99, 102, 241, 0.1);
    transform: translateY(1px);
  }
}
</style>
